# Generated by Django 4.0.1 on 2022-06-26 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scrabble_kit_app', '0002_alter_scrabbleset_tile_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrabbleset',
            name='tile_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scrabble_kit_app.scrabblewordlength'),
        ),
    ]
