# Generated by Django 4.0.1 on 2022-07-13 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrabble_kit_app', '0003_alter_scrabbleset_tile_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scrabbleset',
            name='tile_id',
        ),
    ]
