# Generated by Django 4.0.1 on 2022-07-23 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrabble_kit_app', '0005_scrabbleset_tile_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrabbleset',
            name='user_tile',
            field=models.CharField(max_length=1),
        ),
    ]
