# Generated by Django 4.0.1 on 2022-07-23 16:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrabble_kit_app', '0006_alter_scrabbleset_tile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrabbleset',
            name='user_tile',
            field=models.CharField(max_length=1, validators=[django.core.validators.RegexValidator('^[a-zA-Z-]*$', 'Only letters and special character "-" are allowed.')]),
        ),
    ]
