# Generated by Django 4.0.1 on 2023-02-26 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scrabble_kit_app', '0007_alter_scrabbleset_tile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrabbleset',
            name='tile_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tiles_set', to='scrabble_kit_app.scrabblewordlength'),
        ),
    ]
