# Generated by Django 4.0.1 on 2023-03-26 10:40

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scrabble_kit_app', '0008_alter_scrabbleset_tile_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoardScrabbleSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board_tile', models.CharField(max_length=1, validators=[django.core.validators.RegexValidator('^[a-zA-Z]*$', 'Only letters and special character "-" are allowed.')])),
            ],
        ),
        migrations.CreateModel(
            name='UserScrabbleSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_tile', models.CharField(max_length=1, validators=[django.core.validators.RegexValidator('^[a-zA-Z-]*$', 'Only letters and special character "-" are allowed.')])),
            ],
        ),
        migrations.RemoveField(
            model_name='scrabblewordlength',
            name='word_length',
        ),
        migrations.AddField(
            model_name='scrabblewordlength',
            name='board_tiles',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0, 'Min. value to enter is 0')]),
        ),
        migrations.AddField(
            model_name='scrabblewordlength',
            name='user_word_length',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(2, 'Min. value to enter is 2'), django.core.validators.MaxValueValidator(7, 'Max. value to enter is 7')]),
        ),
        migrations.DeleteModel(
            name='ScrabbleSet',
        ),
        migrations.AddField(
            model_name='userscrabbleset',
            name='user_tile_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_tile_rel', to='scrabble_kit_app.scrabblewordlength'),
        ),
        migrations.AddField(
            model_name='boardscrabbleset',
            name='board_tile_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='board_tile_rel', to='scrabble_kit_app.scrabblewordlength'),
        ),
    ]
